=== ADTRAN/ipfixcol/tools/fbitdump/doc/fbitdump.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<!--=========== Elements: The root element is configuration ============-->
	<xs:element name="configuration" type="configurationType"/>
	
	<xs:element name="columns" type="columnsType"/>	
	<xs:element name="summary" type="summaryType"/>
	<xs:element name="output" type="outputType"/>
	
	<xs:element name="column" type="columnType"/>
	
	<xs:element name="format" type="formatType"/>
	<xs:element name="formatName" type="xs:string"/>
	<xs:element name="formatString" type="xs:string"/>
	
	<xs:element name="alias" type="aliasType"/>
	<xs:element name="alignLeft" type="alignLeftType"/>
	<xs:element name="default-value" type="xs:string"/>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="value" type="valueType" />
	<xs:element name="element" type="elementType"/>
	
	<xs:element name="operation" type="operationType"/>
	<xs:element name="arg1" type="aliasType"/>
	<xs:element name="arg2" type="aliasType"/>
	<xs:element name="width" type="xs:integer"/>
	
	<!--============================ Complex Types =========================-->
	
	<xs:complexType name="elementType">
		<xs:simpleContent>
			<xs:extension base="columnNameType">
				<xs:attribute name="aggregation" type="aggregationType" />
				<xs:attribute name="parts" type="xs:integer"/>
				<xs:attribute name="semantics" type="plainSemanticsType"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="configurationType">
		<xs:sequence>
			<xs:element ref="columns"/>
			<xs:element ref="summary"/>
			<xs:element ref="output"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="columnType">
		<xs:sequence>
			<xs:element ref="name"/>
			<xs:element ref="alias" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element ref="width" minOccurs="0"/>
			<xs:element ref="alignLeft" minOccurs="0"/>
			<xs:element ref="default-value" minOccurs="0"/>
			<xs:element ref="value"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="outputType">
		<xs:sequence>
			<xs:element ref="format" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="formatType">
		<xs:sequence>
			<xs:element ref="formatName"/>
			<xs:element ref="formatString"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="alignLeftType" />
	
	<xs:complexType name="valueType">
		<xs:choice>
			<xs:element ref="element"/>
			<xs:element ref="operation"/>
		</xs:choice>
		<xs:attribute name="type" use="required" type="valueTypeType"/>
	</xs:complexType>
	
	<xs:complexType name="columnsType">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="column"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="summaryType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="column" type="aliasType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="operationType">
		<xs:sequence>
			<xs:element ref="arg1"/>
			<xs:element ref="arg2"/>
		</xs:sequence>
		<xs:attribute name="name" use="required" type="operationNameType"/>
		<xs:attribute name="semantics" type="operationSemanticsType"/>
	</xs:complexType>
	
	<!--====================== Simple Types ================================-->
	
	<xs:simpleType name="columnNameType">
		<xs:restriction base="xs:string">
			<xs:pattern value="e[0-9]+id[0-9]+(p[0-9]+)?|"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="aliasType">
		<xs:restriction base="xs:string">
			<xs:pattern value="%[a-zA-Z0-9]+"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="valueTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="plain" />
			<xs:enumeration value="operation" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="aggregationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="sum"></xs:enumeration>
			<xs:enumeration value="min"></xs:enumeration>
			<xs:enumeration value="max"></xs:enumeration>
			<xs:enumeration value="avg"></xs:enumeration>
			<xs:enumeration value="count"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="plainSemanticsType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ipv4"></xs:enumeration>
			<xs:enumeration value="ipv6"></xs:enumeration>
			<xs:enumeration value="tmstmp64"></xs:enumeration>
			<xs:enumeration value="tmstmp32"></xs:enumeration>
			<xs:enumeration value="tcpflags"></xs:enumeration>
			<xs:enumeration value="flows"></xs:enumeration>
			<xs:enumeration value="protocol"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="operationNameType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="+"></xs:enumeration>
			<xs:enumeration value="-"></xs:enumeration>
			<xs:enumeration value="/"></xs:enumeration>
			<xs:enumeration value="*"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="operationSemanticsType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="duration"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== ADTRAN/ipfixcol/tools/fbitdump/fbitdump.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="fbitdump.xsd">
<!-- 
	This is configuration XML for fbitdump utility
	
	The rules for printing columns are defined here. Each column has one column element which contains:
		name: Name of the column
		width: Width of the column, default is 0
		alias: Alias(es) of the columns, used for operations and custom formatting
		default-value: Defines what to show when table does not have this column
		value: Defines where to get actual value
			value can be of several types:
				plain: just take specified element value for input. Value can be entered as fastbit 
					   column name or 'alias' to plain type
				operation: takes 'arg1' and 'arg2' and performs operation with name from attribute 'name', which
							is one of '+', '-', '/', '*'
							   Operation arguments can be only of plain and operation types and alias to plain type must be used
							   Currently operations are working with integers up to uint64 (int64 is converted to uint64). 
			elements under <value type="plain"> have attribute 'parts'. This specifies to how many columns in database
				is this element splitted.  
			elements under <value type="plain"> have attribute 'semantics'. There are several pre-defined
				options to format ouput columns: as
				'ipv4'	 : expects uint32 column and prints it as IPv4 address
				'ipv6'	 : expects uint64 column and prints it as IPv6 address. 'parts' attribute must be set to 2 
				'tmstmp64': expects uint64 column (miliseconds since 1970) and prints it as timestamp
				'tmstmp32': expects uint32 column (seconds since 1970) and prints it as timestamp
				'tcpflags' : expects uint8 column and print it as TCP flags
				'protocol' : expects uint8 column and prints a name of corresponding IP protocol
				'flows'	: this is special column with no relation to the database. It is always computed as number of flows
			elements under <value type="operation"> can also have attribute 'semantics'. Currently only following can be used:
				'duration': formats miliseconds as seconds with precision 3.
			elements under <value type="plain"> have attribute 'aggregation'. This determines how the columns is
				aggregated. If attribute is empty, column is not aggregated. Supported values are: 'min', 'max', 'sum', 'avg', 'count'
				
				
	Examples are shown below
 -->
<columns>
	<column>
		<name>Date flow start</name>
		<alias>%ts</alias>
		<width>23</width>
		<value type="plain">
			<element semantics="tmstmp64" aggregation="min">e0id152</element>
		</value>
	</column>
	<column>
		<name>Date flow end</name>
		<alias>%te</alias>
		<width>23</width>
		<value type="plain">
			<element semantics="tmstmp64" aggregation="max">e0id153</element>
		</value>
	</column>
	<column>
		<name>Date flow start</name>
		<alias>%ts32</alias>
		<width>23</width>
		<value type="plain">
			<element semantics="tmstmp32" aggregation="min">e0id150</element>
		</value>
	</column>
	<column>
		<name>Date flow end</name>
		<alias>%te32</alias>
		<width>23</width>
		<value type="plain">
			<element semantics="tmstmp32" aggregation="max">e0id151</element>
		</value>
	</column>
	<column>
		<name>Duration</name>
		<alias>%td</alias>
		<alias>%duration</alias>
		<width>9</width>
		<value type="operation">
			<operation name="-" semantics="duration">
				<arg1>%te</arg1>
				<arg2>%ts</arg2>
			</operation>
		</value>
	</column>
	<column>
		<name>Proto</name>
		<alias>%pr</alias>
		<alias>%proto</alias>
		<width>10</width>
		<value type="plain">
			<element semantics="protocol">e0id4</element>
		</value>
	</column>
	<column>
		<name>Src IPv4</name>
		<alias>%sa4</alias>
		<alias>%srcip4</alias>
		<width>16</width>
		<value type="plain">
			<element semantics="ipv4">e0id8</element>
		</value>
	</column>
	<column>
		<name>Src IPv6</name>
		<alias>%sa6</alias>
		<alias>%srcip6</alias>
		<width>39</width>
		<value type="plain">
			<element semantics="ipv6" parts="2">e0id27</element>
		</value>
	</column>
	<column>
		<name>Dst IPv4</name>
		<alias>%da4</alias>
		<alias>%dstip4</alias>
		<width>16</width>
		<value type="plain">
			<element semantics="ipv4">e0id12</element>
		</value>
	</column>
	<column>
		<name>Dst IPv6</name>
		<alias>%da6</alias>
		<alias>%dstip6</alias>
		<width>39</width>
		<value type="plain">
			<element semantics="ipv6" parts="2">e0id28</element>
		</value>
	</column>
	<column>
		<name>sPort</name>
		<alias>%sp</alias>
		<alias>%srcport</alias>
		<width>5</width>
		<alignLeft/>
		<default-value>0</default-value>
		<value type="plain">
			<element>e0id7</element>
		</value>
	</column>
	<column>
		<name>dPort</name>
		<alias>%dp</alias>
		<alias>%dstport</alias>
		<width>5</width>
		<alignLeft/>
		<default-value>0</default-value>
		<value type="plain">
			<element>e0id11</element>
		</value>
	</column>
	<column>
		<name>ICMP type</name>
		<alias>%icmptype</alias>
		<width>9</width>
		<default-value>0</default-value>
		<value type="plain">
			<element>e0id32</element>
		</value>
	</column>
	<column>
		<name>Flags</name>
		<alias>%flg</alias>
		<width>6</width>
		<default-value>......</default-value>
		<value type="plain">
			<element semantics="tcpflags">e0id6</element>
		</value>
	</column>
	<column>
		<name>Tos</name>
		<alias>%tos</alias>
		<width>4</width>
		<default-value>0</default-value>
		<value type="plain">
			<element>e0id5</element>
		</value>
	</column>
	<column>
		<name>Packets</name>
		<alias>%pkt</alias>
		<width>7</width>
		<value type="plain">
			<element aggregation="sum">e0id2</element>
		</value>
	</column>
	<column>
		<name>Bytes</name>
		<alias>%byt</alias>
		<width>8</width>
		<value type="plain">
			<element aggregation="sum">e0id1</element>
		</value>
	</column>
	<column>
		<name>pps</name>
		<alias>%pps</alias>
		<width>8</width>
		<value type="operation">
			<operation name="/">
				<arg1>%pkt</arg1>
				<arg2>%td</arg2>
			</operation>
		</value>
	</column>
	<column>
		<name>bps</name>
		<alias>%bps</alias>
		<width>8</width>
		<value type="operation">
			<operation name="/">
				<arg1>%byt</arg1>
				<arg2>%td</arg2>
			</operation>
		</value>
	</column>
	<column>
		<name>Bpp</name>
		<alias>%bpp</alias>
		<width>8</width>
		<value type="operation">
			<operation name="/">
				<arg1>%byt</arg1>
				<arg2>%pkt</arg2>
			</operation>
		</value>
	</column>
	<column>
		<name>Src AS</name>
		<alias>%sas</alias>
		<width>8</width>
		<value type='plain'>
			<element>e0id16</element>
		</value>
	</column>
	<column>
		<name>Dst AS</name>
		<alias>%das</alias>
		<width>8</width>
		<value type='plain'>
			<element>e0id17</element>
		</value>
	</column>
	<column>
		<name>ip Ver.</name>
		<alias>%ipv</alias>
		<width>7</width>
		<value type="plain">
			<element>e0id60</element>
		</value>
	</column>
	<column>
		<name>Input</name>
		<alias>%in</alias>
		<width>8</width>
		<value type='plain'>
			<element>e0id10</element>
		</value>
	</column>
	<column>
		<name>Output</name>
		<alias>%out</alias>
		<width>8</width>
		<value type='plain'>
			<element>e0id14</element>
		</value>
	</column>
	<column>
		<name>Flows</name>
		<alias>%fl</alias>
		<width>5</width>
		<default-value>1</default-value>
		<value type="plain">
			<element semantics="flows" aggregation="count"></element>
		</value>
	</column>
	<column>
		<name>If. Description</name>
		<alias>%ifdesc</alias>
		<width>15</width>
		<default-value>-</default-value>
		<value type="plain">
			<element>e0id83</element>
		</value>
	</column>
</columns>

<!-- summary section contain aliases of columns that can be used for statistics summary, i.e. totals
	only plain columns can be used -->
<summary>
	<column>%pkt</column>
	<column>%byt</column>
	<column>%fl</column>
</summary>
</configuration>
